#!/usr/bin/env node
/**
 * Render the app's icon files from the single geometry definition in
 * `src/lib/brand/logo.ts`.
 *
 *   node scripts/make-icons.mjs           # write static/*.svg|png, then report
 *   node scripts/make-icons.mjs --check   # report only, write nothing
 *
 * Why a script instead of hand-drawn files: the title-bar mark, the favicon and
 * the installed icon have to stay the same animal, and the only way to be sure
 * is for all of them to come out of one function. Node 24 strips the TypeScript
 * types on import, and `sharp` (already in the tree, used by nothing at runtime)
 * rasterises the SVG.
 *
 * The PNGs exist for the platforms that will not take an SVG: Android's install
 * prompt wants 192 and 512, and iOS `apple-touch-icon` has never supported SVG —
 * it silently falls back to a screenshot of the page, which is what used to
 * happen here.
 */

import { mkdir, writeFile } from 'node:fs/promises'
import { fileURLToPath, pathToFileURL } from 'node:url'
import path from 'node:path'
import sharp from 'sharp'

const root = path.resolve(fileURLToPath(new URL('..', import.meta.url)))
const check = process.argv.includes('--check')

const { DEFAULT_APP_ICON, iconSvg, iconVariant, ROOMY_RADIUS, SAFE_RADIUS } = await import(
  pathToFileURL(path.join(root, 'src/lib/brand/logo.ts')).href
)

const v = iconVariant(DEFAULT_APP_ICON)

/** `bleed` is for platforms that apply their own mask, so the colour must reach every edge. */
const TARGETS = [
  { file: 'icon-192.png', size: 192, opts: { fit: ROOMY_RADIUS } },
  { file: 'icon-512.png', size: 512, opts: { fit: ROOMY_RADIUS } },
  { file: 'icon-maskable-512.png', size: 512, opts: { fit: SAFE_RADIUS, bleed: true } },
  { file: 'apple-touch-icon.png', size: 180, opts: { fit: SAFE_RADIUS, bleed: true } },
]

const SVG_HEADER = `<!--
  乔巴 — the app icon (the "${v.label}" colourway, which is the default).

  Generated by scripts/make-icons.mjs from src/lib/brand/logo.ts — edit that file,
  not this one. This is the pre-JavaScript icon: the page shows it before anything
  else runs, and it is what static/manifest.webmanifest points at.
-->
`

const ascii = (data, info) => {
  const ramp = ' .:-=+*#%@'
  const lines = []
  for (let y = 0; y < info.height; y++) {
    let line = ''
    for (let x = 0; x < info.width; x++) {
      const l = data[y * info.width + x]
      line += ramp[Math.min(ramp.length - 1, Math.floor(((255 - l) / 256) * ramp.length))]
    }
    lines.push(line)
  }
  return lines.join('\n')
}

/**
 * How far the outermost non-background pixel sits from the centre, in 512ths.
 * This is the number that decides whether a launcher mask may clip the antlers.
 */
async function reach(png, channels) {
  const { data, info } = await sharp(png)
    .resize(512, 512, { fit: 'fill' })
    .ensureAlpha()
    .raw()
    .toBuffer({ resolveWithObject: true })
  const [br, bg_, bb] = [1, 3, 5].map((i) => parseInt(v.bg.slice(i, i + 2), 16))
  const c = 256
  let max = 0
  for (let y = 0; y < info.height; y++) {
    for (let x = 0; x < info.width; x++) {
      const o = (y * info.width + x) * info.channels
      // Transparent pixels are the rounded corners, not the mascot: a corner of
      // the canvas is 362 from the centre, which is not something to report.
      if (channels === 4 && data[o + 3] < 200) continue
      const d = Math.hypot(data[o] - br, data[o + 1] - bg_, data[o + 2] - bb)
      if (d > 30) max = Math.max(max, Math.hypot(x + 0.5 - c, y + 0.5 - c))
    }
  }
  return max
}

const report = []

if (!check) await mkdir(path.join(root, 'static'), { recursive: true })

// The SVG, written from the same function the runtime uses.
const svg = SVG_HEADER + iconSvg(DEFAULT_APP_ICON) + '\n'
if (!check) await writeFile(path.join(root, 'static/icon.svg'), svg)
report.push(`icon.svg             ${String(Buffer.byteLength(svg)).padStart(7)} B   (${iconSvg(DEFAULT_APP_ICON).length} chars, ${v.label})`)

for (const t of TARGETS) {
  const png = await sharp(Buffer.from(iconSvg(DEFAULT_APP_ICON, t.opts))).resize(t.size, t.size).png({ compressionLevel: 9 }).toBuffer()
  if (!check) await writeFile(path.join(root, 'static', t.file), png)
  const meta = await sharp(png).metadata()
  const r = await reach(png, meta.channels)
  const limit = t.opts.bleed ? SAFE_RADIUS : ROOMY_RADIUS
  report.push(
    `${t.file.padEnd(21)}${String(png.length).padStart(7)} B   ${meta.width}×${meta.height}   mark reaches r=${Math.round(r)} (limit ${limit}${r <= limit ? ' ✅' : ' ❌'})`,
  )
  // A look at the small size, where an icon either works or turns to mud.
  if (t.size <= 192) {
    const { data, info } = await sharp(png)
      .flatten({ background: v.bg })
      .resize(40, 40, { fit: 'fill' })
      .greyscale()
      .raw()
      .toBuffer({ resolveWithObject: true })
    report.push(ascii(data, info).split('\n').map((l) => `  ${l}`).join('\n'))
  }
}

console.log(report.join('\n'))
if (check) console.log('\n(--check: nothing written)')
